route:
  group_by: ['severity']
  group_wait: 1s
  group_interval: 1m
  repeat_interval: 5m
  receiver: 'telegram-alert-bot'

receivers:
  - name: 'telegram-alert-bot'
    telegram_configs:
      - send_resolved: true
        bot_token: "7613253333:AAH_mhsvqRiF_d_YeguNS5W-Vz8W4LbR3s4"
        chat_id: 896890026
        message: |
          [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }}
          Details:
          {{ range .Alerts }}
            - alertname: {{ .Labels.alertname }}
            - instance: {{ .Labels.instance }}
            - severity: {{ .Labels.severity }}
            - description: {{ .Annotations.description }}
          {{ end }}
